Update version to 1.0.0
django-webpack/django-webpack-loader pull request #269
Opened 2021-05-06 13:57 UTC by rvlb

2021-05-06 14:18 UTC, fjsj requested changes
@rvlb please check the issues on milestone 1.0.0: https://github.com/django-webpack/django-webpack-loader/milestone/1

2021-05-12 12:54 UTC, fjsj commented on README.md
> +Test cases cover Django>=2.0 on Python>=3.5. 100% code coverage is the target so we can be sure everything works anytime. It should probably work on older version of django as well but the package do
Can we add code coverage badges and supported version badges?

2021-05-12 12:56 UTC, fjsj commented on examples/hot-reload/README.md
> -Now you can make changes to `assets/js/app.jsx` and the changes will show up in the browser automagically.
Any reason to remove this line?

2021-05-12 12:57 UTC, fjsj requested changes
Overall looking nice. Some corrections TODO:

- We should add db.sqlite3 to .gitignore. This PR is adding `examples/simple/db.sqlite3`.
- Check inline comments.

2021-05-12 12:59 UTC, fjsj commented on webpack_loader/loader.py
> +        relpath = os.path.normpath(
Is this necessary?

2021-05-12 13:09 UTC, rvlb commented on webpack_loader/loader.py
> +        relpath = os.path.normpath(
#207

2021-05-12 19:23 UTC, fjsj approved these changes
LGTM, thanks!

2021-05-12 19:26 UTC, merged