Handle transformed assets URL
django-webpack/django-webpack-loader pull request #397
Opened 2024-03-29 08:53 UTC by batistadasilva

Adding the following template tag

```
{% webpack_asset 'path/to/original/file' %}
```

Fixes https://github.com/django-webpack/django-webpack-loader/issues/343

Depends on https://github.com/django-webpack/webpack-bundle-tracker/pull/125

2024-04-01 12:59 UTC, fjsj commented on webpack_loader/utils.py
> +def get_asset(asset_name, config='DEFAULT'):
Please add a docstring similar to the one from `get_static`, but clarify why this is different.

2024-04-01 13:01 UTC, fjsj commented on webpack_loader/utils.py
> +    return get_static(asset['name'], config)
I guess this should not support the old `asset_name` based lookup to avoid confusion.

2024-04-01 13:02 UTC, fjsj commented on webpack_loader/loaders.py
> +        return asset
I think this should read like this:
```python
    def get_asset_by_source_filename(self, name):
        files = self.get_assets()["assets"]
        return next((x for x in files if x.get("sourceFilename") == name), None)
```

2024-04-01 13:02 UTC, fjsj requested changes
Overall LGTM, but please check suggestions. Thanks for the contribution!

2024-04-02 09:49 UTC, batistadasilva commented
@fjsj Thanks for the review!

Let me know if all changes fit the requirements

2024-04-02 13:01 UTC, fjsj approved these changes
Thanks, looks great.

2024-04-02 13:02 UTC, merged

2024-04-04 13:12 UTC, fjsj commented
Released at 3.1.0, thanks again @batistadasilva 
If you have time, could you make a PR to update the README explaining how to use `webpack_asset`?